name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      
    steps:
    - name: check tests
      uses: actions/checkout@main
      with:
        name: mhseufrasio/.github-workflows
    - name: Checkout repository
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Clone BACK repository
      run: |
        git clone https://github.com/IFCE-LASIC/lasic-ches-back.git
        mhseufrasio
        ${{ secrets.TOKEN_GITHUB }}
    - name: Run Tests
      run: python -m robot --outputdir results testcases/functional_tests
    - name: Run Tests and creat report
      run: python -m robot -d reports -x junit-report.xml "testcases/functional_tests"
    - name: Run Robot Framework tests and generate report
      run: |
        echo "ROBOT_RC=$" >> "$GITHUB_ENV"
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-test-results
        path: results
    - name: Notificação Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Testes fializados
        format: results/log.html
